# Generated by Django 4.1.2 on 2022-11-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=60, verbose_name='Nome Completo')),
                ('documento', models.CharField(choices=[('RG', 'Registro Geral'), ('CPF', 'Cadastro de Pessoa Física')], max_length=10, verbose_name='Tipo de documento')),
                ('n_documento', models.CharField(max_length=60, verbose_name='Número do documento')),
                ('data_nascimento', models.DateTimeField(verbose_name='Data de nascimento')),
            ],
        ),
    ]
