# Generated by Django 4.1.2 on 2022-12-13 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='morador',
            options={},
        ),
    ]
