# Generated by Django 4.1.2 on 2022-12-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_morador_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='anfitrião',
            name='cep',
            field=models.CharField(max_length=70, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='anfitrião',
            name='comp_endereco',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Se tiver complemento do endereço'),
        ),
        migrations.AlterField(
            model_name='anfitrião',
            name='data_casamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de casamento'),
        ),
        migrations.AlterField(
            model_name='anfitrião',
            name='n_pessoas_familia',
            field=models.CharField(default='2', max_length=17, verbose_name='Quantas pessoas possuem na família (contando com o anfitrião).'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anfitrião',
            name='profissao',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Profissão'),
        ),
    ]
