# Generated by Django 4.1.2 on 2022-11-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_morador'),
    ]

    operations = [
        migrations.AddField(
            model_name='morador',
            name='trabalhando',
            field=models.CharField(choices=[('Sim', 'Trabalha'), ('Não', 'Não Trabalha')], default='Sim', max_length=20, verbose_name='Sim ou Não'),
            preserve_default=False,
        ),
    ]
