# Generated by Django 4.1.2 on 2022-11-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_morador_trabalhando'),
    ]

    operations = [
        migrations.AddField(
            model_name='morador',
            name='estudando',
            field=models.CharField(choices=[('Sim', 'Estuda'), ('Não', 'Não Estuda')], default='Sim', max_length=10, verbose_name='Tipo de documento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='morador',
            name='grau_parentesco',
            field=models.CharField(choices=[('Esposo/a', 'Esposo/a'), ('Filho/a', 'Filho/a'), ('Irmão/ã', 'Filho/ã'), ('Avô/ó', 'Avô/ó'), ('Sobrinho/a', 'Sobrinho/a'), ('Neto/a', 'Neto/a'), ('Tio/a', 'Tio/a'), ('Primo/a', 'Primo/a'), ('Genro/Nora', 'Genro/Nora'), ('Outros', 'Outros')], default='Esposo/a', max_length=10, verbose_name='Tipo de documento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='morador',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=10, verbose_name='Tipo de documento'),
            preserve_default=False,
        ),
    ]
