# Generated by Django 4.1.2 on 2022-12-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_anfitrião_cep_alter_anfitrião_comp_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anfitrião',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('Outro', 'Outro')], default='M', max_length=10, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='estudando',
            field=models.CharField(choices=[('Sim', 'Estuda'), ('Não', 'Não Estuda')], max_length=10, verbose_name='Estuda?'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='grau_parentesco',
            field=models.CharField(choices=[('Esposo/a', 'Esposo/a'), ('Pai', 'Pai'), ('Mãe', 'Mãe'), ('Filho/a', 'Filho/a'), ('Irmão/ã', 'Irmão/ã'), ('Avô/ó', 'Avô/ó'), ('Sobrinho/a', 'Sobrinho/a'), ('Neto/a', 'Neto/a'), ('Tio/a', 'Tio/a'), ('Primo/a', 'Primo/a'), ('Genro/Nora', 'Genro/Nora'), ('Outros', 'Outros')], max_length=10, verbose_name='Qual grau de parentesco?'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('Outro', 'Outro')], max_length=10, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='trabalhando',
            field=models.CharField(choices=[('Sim', 'Trabalha'), ('Não', 'Não Trabalha')], max_length=20, verbose_name='Trabalha?'),
        ),
    ]
