# Generated by Django 4.1.2 on 2022-11-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_anfitrião_alter_morador_n_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anfitrião',
            name='filhos',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='S', max_length=17, verbose_name='Possui filhos'),
        ),
        migrations.AddField(
            model_name='anfitrião',
            name='filhos_menor_quartorze_anos',
            field=models.CharField(max_length=17, null=True, verbose_name='Se possuir filhos, informar se possui filhos menores de 14 anos'),
        ),
        migrations.AddField(
            model_name='anfitrião',
            name='filhos_residencia',
            field=models.CharField(max_length=17, null=True, verbose_name='Se possuir filhos, informar quantos moram junto'),
        ),
        migrations.AddField(
            model_name='anfitrião',
            name='n_carteira_trabalho',
            field=models.IntegerField(null=True, verbose_name='Nº Careteira de Trabalho'),
        ),
        migrations.AddField(
            model_name='anfitrião',
            name='n_filhos',
            field=models.CharField(max_length=17, null=True, verbose_name='Se possuir filhos, informar o Nº'),
        ),
        migrations.AddField(
            model_name='anfitrião',
            name='praticante',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não'), ('A', 'As vezes')], default='S', max_length=17, verbose_name='Praticante'),
        ),
        migrations.AddField(
            model_name='anfitrião',
            name='profissao',
            field=models.CharField(default='s', max_length=60, verbose_name='Profissão'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anfitrião',
            name='religiao',
            field=models.CharField(choices=[('C', 'Católico'), ('E', 'Evangélico'), ('O', 'Outra')], default='C', max_length=17, verbose_name='Religião'),
        ),
        migrations.AddField(
            model_name='anfitrião',
            name='situacao_atual',
            field=models.CharField(choices=[('T', 'Trabalhando'), ('D', 'Desempregado'), ('Af', 'Afastado'), ('Ap', 'Aposentado'), ('P', 'Pensionista'), ('O', 'Outros')], default='T', max_length=17, verbose_name='Situação atual'),
        ),
        migrations.AddField(
            model_name='anfitrião',
            name='telefone',
            field=models.IntegerField(null=True, verbose_name='Celular ou Telefone'),
        ),
        migrations.AlterField(
            model_name='anfitrião',
            name='cpf',
            field=models.DecimalField(decimal_places=0, max_digits=11, null=True, verbose_name='Número do CPF'),
        ),
        migrations.AlterField(
            model_name='anfitrião',
            name='data_casamento',
            field=models.DateTimeField(null=True, verbose_name='Data de casamento'),
        ),
        migrations.AlterField(
            model_name='anfitrião',
            name='escolaridade',
            field=models.CharField(choices=[('F', 'Fundamental'), ('M', 'Médio'), ('SI', 'Superior Inc.'), ('SC', 'Superior Completo'), ('S', 'Sem escolaridade')], default='F', max_length=17, verbose_name='Escolaridade'),
        ),
        migrations.AlterField(
            model_name='anfitrião',
            name='estado_civil',
            field=models.CharField(choices=[('S', 'Solteiro/a'), ('C', 'Casado/a'), ('V', 'Viúvo/a'), ('S', 'Separado/a'), ('O', 'Outros')], default='C', max_length=17, verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='anfitrião',
            name='rg',
            field=models.DecimalField(decimal_places=0, max_digits=7, null=True, verbose_name='Número do RG'),
        ),
        migrations.AlterField(
            model_name='anfitrião',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='anfitrião',
            name='tipo_residencia',
            field=models.CharField(choices=[('P', 'Própria'), ('A', 'Alugada'), ('M', 'Moro com Parentes'), ('O', 'Outro')], max_length=17, verbose_name='Tipo de Residência'),
        ),
    ]
