# Generated by Django 4.1.2 on 2022-11-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_anfitrião_data_casamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anfitrião',
            name='alguem_beneficio_auxilio',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='S', max_length=17, verbose_name='Alguém recebe algum benefício/auxílio do governo?'),
        ),
        migrations.AddField(
            model_name='anfitrião',
            name='alguem_impossibilitado',
            field=models.CharField(choices=[('D', 'Doente'), ('DF', 'Def. Físico'), ('N', 'Não')], default='D', max_length=17, verbose_name='Na família tem alguém:'),
        ),
        migrations.AddField(
            model_name='anfitrião',
            name='alguem_posto_saude',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='S', max_length=17, verbose_name='Alguém frequenta posto de saúde?'),
        ),
        migrations.AddField(
            model_name='anfitrião',
            name='bairro',
            field=models.CharField(max_length=70, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='anfitrião',
            name='beneficio_auxilio',
            field=models.CharField(max_length=17, null=True, verbose_name='Se alguém receber algum auxilio/beneficio do governo, informar-lo'),
        ),
        migrations.AddField(
            model_name='anfitrião',
            name='cidade',
            field=models.CharField(max_length=70, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='anfitrião',
            name='comp_endereco',
            field=models.CharField(max_length=50, null=True, verbose_name='Se tiver complemento do endereço'),
        ),
        migrations.AddField(
            model_name='anfitrião',
            name='endereco',
            field=models.CharField(max_length=100, null=True, verbose_name='Av/Rua do endereço'),
        ),
        migrations.AddField(
            model_name='anfitrião',
            name='estado',
            field=models.CharField(max_length=70, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='anfitrião',
            name='n_endereco',
            field=models.CharField(max_length=30, null=True, verbose_name='Nº do endereço'),
        ),
        migrations.AddField(
            model_name='anfitrião',
            name='posto_bairro',
            field=models.CharField(max_length=17, null=True, verbose_name='Se alguém frequentar o posto, informar o posto e o bairro'),
        ),
        migrations.AddField(
            model_name='anfitrião',
            name='tipo_deficiencia',
            field=models.CharField(max_length=17, null=True, verbose_name='Se tiver alguém deficiente, informar o tipo da deficiência'),
        ),
        migrations.AddField(
            model_name='anfitrião',
            name='tipo_doenca',
            field=models.CharField(max_length=17, null=True, verbose_name='Se tiver alguém doente, informar o tipo de doença'),
        ),
        migrations.AlterField(
            model_name='anfitrião',
            name='tipo_residencia',
            field=models.CharField(choices=[('P', 'Própria'), ('A', 'Alugada'), ('M', 'Moro com Parentes'), ('O', 'Outro')], default='A', max_length=17, verbose_name='Tipo de Residência'),
        ),
    ]
