# Generated by Django 4.1.2 on 2022-11-15 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_anfitrião_alguem_beneficio_auxilio_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='anfitrião',
            table='Família',
        ),
    ]
