# Generated by Django 4.1.2 on 2022-11-15 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_anfitrião_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='morador',
            name='anfitriao',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='moradores', to='base.anfitrião'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anfitrião',
            name='cpf',
            field=models.IntegerField(max_length=11, null=True, verbose_name='Número do CPF'),
        ),
        migrations.AlterField(
            model_name='anfitrião',
            name='rg',
            field=models.IntegerField(max_length=7, null=True, verbose_name='Número do RG'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de nascimento'),
        ),
        migrations.AlterModelTable(
            name='anfitrião',
            table=None,
        ),
    ]
