# Generated by Django 4.1.2 on 2022-11-15 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_morador_anfitriao_alter_anfitrião_cpf_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='anfitrião',
            table='Família',
        ),
    ]
