# Generated by Django 4.1.2 on 2022-11-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_anfitrião_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anfitrião',
            options={'ordering': ['nome_completo']},
        ),
        migrations.AlterModelOptions(
            name='morador',
            options={'verbose_name_plural': 'Moradores'},
        ),
        migrations.AlterField(
            model_name='anfitrião',
            name='beneficio_auxilio',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Se alguém receber algum auxilio/beneficio do governo, informar-lo'),
        ),
        migrations.AlterField(
            model_name='anfitrião',
            name='cpf',
            field=models.IntegerField(blank=True, max_length=11, null=True, verbose_name='Número do CPF'),
        ),
        migrations.AlterField(
            model_name='anfitrião',
            name='filhos_menor_quartorze_anos',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Se possuir filhos, informar se possui filhos menores de 14 anos'),
        ),
        migrations.AlterField(
            model_name='anfitrião',
            name='filhos_residencia',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Se possuir filhos, informar quantos moram junto'),
        ),
        migrations.AlterField(
            model_name='anfitrião',
            name='n_carteira_trabalho',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nº Careteira de Trabalho'),
        ),
        migrations.AlterField(
            model_name='anfitrião',
            name='n_filhos',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Se possuir filhos, informar o Nº'),
        ),
        migrations.AlterField(
            model_name='anfitrião',
            name='posto_bairro',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Se alguém frequentar o posto, informar o posto e o bairro'),
        ),
        migrations.AlterField(
            model_name='anfitrião',
            name='rg',
            field=models.IntegerField(blank=True, max_length=7, null=True, verbose_name='Número do RG'),
        ),
        migrations.AlterField(
            model_name='anfitrião',
            name='tipo_deficiencia',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Se tiver alguém deficiente, informar o tipo da deficiência'),
        ),
        migrations.AlterField(
            model_name='anfitrião',
            name='tipo_doenca',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Se tiver alguém doente, informar o tipo de doença'),
        ),
    ]
