# Generated by Django 4.1.2 on 2022-11-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_anfitrião_options_alter_morador_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anfitrião',
            name='n_pessoas_familia',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Quantas pessoas possuem na família (contando com o anfitrião).'),
        ),
    ]
